{
 "title": "Online Boutique",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "namespace", "query": "online-boutique" },
   { "name": "type", "query": ".+" },
   { "name": "cluster" }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_app_info{dest_namespace=~\"$namespace\", health_status=\"Healthy\"} or on() vector(0)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_app_info{dest_namespace=~\"$namespace\", sync_status=\"Synced\"}",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Last velero backup status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_last_status{schedule=\"online-boutique\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Certificate Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{exported_namespace=~\"$namespace\"}) by (host) - time()",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=~\"$type\"}) by (workload, workload_type)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=~\"$type\"}\n) by (workload, workload_type)",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=~\"$type\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"online-boutique\"} | json | line_format \"{{.message}}\" | drop app,container_id,message,pod_id,pod_template_hash,service_name,time",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}