# Note: Kustomize pull timeout is global, a value of 27s (the default) applies to the whole kustomization.
# This timeout was increased to 90s using the query string configuration method.
# https://github.com/kubernetes-sigs/kustomize/issues/5298 would greatly reduce this clone time.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
- https://github.com/GoogleCloudPlatform/microservices-demo//kustomize/base?timeout=90s&ref=6af73dcf7fe1ca653d95ae7a29e12faf8cf02964
- frontend-admin-panel.yaml
- ingress.yaml
- dashboard.yaml
- slo.yaml
- velero-backup.yaml
- autoscaling.yaml
components:
- https://github.com/GoogleCloudPlatform/microservices-demo//kustomize/components/network-policies?timeout=90s&ref=6af73dcf7fe1ca653d95ae7a29e12faf8cf02964
- https://github.com/GoogleCloudPlatform/microservices-demo//kustomize/components/non-public-frontend?timeout=90s&ref=6af73dcf7fe1ca653d95ae7a29e12faf8cf02964
- https://github.com/GoogleCloudPlatform/microservices-demo//kustomize/components/cymbal-branding?timeout=90s&ref=6af73dcf7fe1ca653d95ae7a29e12faf8cf02964
patches:
- path: patch-enable-tracing.yaml
- path: patch-frontend-admin-panel.yaml
- path: patch-loadgenerator-config.yaml
