---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
