apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  template:
    spec:
      containers:
      - name: main
        # TODO: Use upstream image when https://github.com/GoogleCloudPlatform/microservices-demo/pull/2775 is released
        image: ghcr.io/aslafy-z/microservices-demo/loadgenerator:483c6f731bb7c408ff5be379683b0ace8ea5833c
        env:
        - name: FRONTEND_ADDR
          value: shop.ref+file://config.yaml#/ingress/domainName+:443
        - name: USERS
          value: "30"
