apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: online-boutique
  labels:
    app.kubernetes.io/type: prod
spec:
  owners:
  - name: oidc:guest@k8saas.io
    kind: User
  namespaceOptions:
    quota: 1
