apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: k8saas-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: online-boutique
    name: in-cluster
  project: default
  source:
    path: online-boutique
    repoURL: http://gitea-http.k8saas-system.svc:3000/root/k8saas-frozen
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
