apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: ecommerce
  labels:
    k8saas.io/tenant: ecommerce
spec:
  owners:
  - name: oidc:guest@k8saas.io
    kind: User
  namespaceOptions:
    quota: 1
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: ecommerce
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: online-boutique
    name: in-cluster
  project: ecommerce
  source:
    path: online-boutique
    repoURL: http://gitea-http.k8saas-system.svc:3000/root/k8saas-frozen
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
